### PR TITLE
Make battery percentage consistent with official app

### PR DESCRIPTION
**Pull request by arnerek**
Should resolve https://github.com/home-assistant/core/issues/100521

### CODE REVIEW

**Review by murkumurdok — APPROVED** [review]

**Comment by onegambler** [comment]
Anyone able to approve and merge this? It has been open for 2 months. It's a very simple change.

Thanks

**Comment by HormCodes** [comment]
Hi @onegambler, thank you for the reminder. I'll try to take a look at this and provide a response next week.

**Comment by greg520820** [comment]
I would consider making the battery voltages user configurable.  

In my case the web app was telling me I had 40% battery life and airthings-ble was indicating 10% battery life.  My airthings wave+ stopped working the next day because of low battery voltage. The airthings-ble was more accurate.   

Some of the issue may be voltage differences vs battery percentage remaining between alkaline and lithium batteries.  Making the voltages configurable would allow the user to make a decision that meets their needs.

**Comment by onegambler** [comment]
The biggest issue that I see is consistency, having different readings between the app and this library is not great.

**Comment by HormCodes** [comment]
Hi @arnerek, we have another PR #27 on the way (currently in testing). The PR is bringing a robust solution for all devices and should resolve the issue. I suggest waiting with the rebase or closing the PR. Anyway, thank you for your contribution and patience.

**Comment by LaStrada** [comment]
The battery sensor was fixed in this PR: https://github.com/Airthings/airthings-ble/pull/27

Closing this ticket.

**Pull request closed without merging**
